[package]
name = "travel-agency"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.24"
sysinfo = "0.30.13"
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }